//! Cross-validation tests comparing Rust implementation against Python golden outputs.
//!
//! These tests verify that the Rust CLIP, BLIP, and service implementations
//! produce equivalent results to the Python backend.
//!
//! Run with: cargo test --test cross_validation
//! Note: Requires golden outputs generated by tests/cross_validation/generate_golden.py

use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("tests/cross_validation/fixtures/golden_outputs")
}

fn golden_exists() -> bool {
    golden_dir().join("clip/test_queries.json").exists()
}

fn load_json(subdir: &str, filename: &str) -> serde_json::Value {
    let path = golden_dir().join(subdir).join(filename);
    let data = fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("Golden output not found: {}", path.display()));
    serde_json::from_str(&data).unwrap()
}

fn load_npy_f32(subdir: &str, filename: &str) -> Vec<f32> {
    let path = golden_dir().join(subdir).join(filename);
    let bytes = fs::read(&path)
        .unwrap_or_else(|_| panic!("Golden output not found: {}", path.display()));

    // Simple .npy parser for 1D float32 arrays
    // Skip the header (first 128 bytes typically) and read f32 values
    // The actual header length is in bytes 8-9 (little-endian u16)
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let data_start = 10 + header_len;
    let float_bytes = &bytes[data_start..];

    float_bytes
        .chunks_exact(4)
        .map(|chunk| f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
        .collect()
}

fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    let dot: f32 = a.iter().zip(b).map(|(x, y)| x * y).sum();
    let norm_a: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let norm_b: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    if norm_a == 0.0 || norm_b == 0.0 {
        return 0.0;
    }
    dot / (norm_a * norm_b)
}

// =============================================================================
// CLIP Tests
// =============================================================================

#[test]
#[ignore] // Requires golden outputs and model download
fn test_clip_text_embeddings_match_python() {
    if !golden_exists() {
        eprintln!("Skipping: golden outputs not generated");
        return;
    }

    let engine = rust_core::clip::ClipEngine::new("/tmp/photosearch_test_models").unwrap();
    let queries: Vec<String> =
        serde_json::from_value(load_json("clip", "test_queries.json")).unwrap();

    for query in &queries {
        let safe_name = query.replace(' ', "_");
        let safe_name = &safe_name[..safe_name.len().min(50)];
        let golden = load_npy_f32("clip", &format!("text_{}.npy", safe_name));
        let rust_emb = engine.encode_text(query).unwrap();

        let sim = cosine_similarity(&golden, &rust_emb);
        assert!(
            sim > 0.99,
            "CLIP text embedding mismatch for '{}': cosine_similarity={:.4} (expected > 0.99)",
            query,
            sim
        );
    }
}

#[test]
#[ignore] // Requires golden outputs and model download
fn test_clip_image_embeddings_match_python() {
    if !golden_exists() {
        eprintln!("Skipping: golden outputs not generated");
        return;
    }

    let engine = rust_core::clip::ClipEngine::new("/tmp/photosearch_test_models").unwrap();
    let image_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("tests/cross_validation/fixtures/test_images");

    for entry in fs::read_dir(&image_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if !["jpg", "jpeg", "png", "webp"].contains(&ext.to_lowercase().as_str()) {
            continue;
        }

        let stem = path.file_stem().unwrap().to_str().unwrap();
        let golden_file = format!("{}_image.npy", stem);
        let golden_path = golden_dir().join("clip").join(&golden_file);
        if !golden_path.exists() {
            continue;
        }

        let golden = load_npy_f32("clip", &golden_file);
        let rust_emb = engine.encode_image(path.to_str().unwrap()).unwrap();

        assert_eq!(rust_emb.len(), 512, "Embedding should be 512-dim");

        let sim = cosine_similarity(&golden, &rust_emb);
        assert!(
            sim > 0.99,
            "CLIP image embedding mismatch for '{}': cosine_similarity={:.4} (expected > 0.99)",
            path.display(),
            sim
        );
    }
}

#[test]
#[ignore] // Requires golden outputs and model download
fn test_clip_cross_modal_scores_match_python() {
    if !golden_exists() {
        eprintln!("Skipping: golden outputs not generated");
        return;
    }

    let scores: serde_json::Map<String, serde_json::Value> =
        serde_json::from_value(load_json("clip", "cross_modal_scores.json")).unwrap();

    let engine = rust_core::clip::ClipEngine::new("/tmp/photosearch_test_models").unwrap();
    let image_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("tests/cross_validation/fixtures/test_images");

    for (key, python_score) in &scores {
        let parts: Vec<&str> = key.split("||").collect();
        if parts.len() != 2 {
            continue;
        }
        let query = parts[0];
        let img_name = parts[1];
        let img_path = image_dir.join(img_name);
        if !img_path.exists() {
            continue;
        }

        let python_score = python_score.as_f64().unwrap() as f32;
        let text_emb = engine.encode_text(query).unwrap();
        let image_emb = engine.encode_image(img_path.to_str().unwrap()).unwrap();
        let rust_score: f32 = text_emb.iter().zip(&image_emb).map(|(a, b)| a * b).sum();

        let diff = (rust_score - python_score).abs();
        assert!(
            diff < 0.01,
            "Cross-modal score mismatch for '{}' x '{}': python={:.4}, rust={:.4}, diff={:.4}",
            query,
            img_name,
            python_score,
            rust_score,
            diff
        );
    }
}

// =============================================================================
// Query Parser Tests
// =============================================================================

#[test]
fn test_query_parser_matches_python() {
    let golden_path = golden_dir().join("query_parser/parsed_queries.json");
    if !golden_path.exists() {
        eprintln!("Skipping: golden outputs not generated");
        return;
    }

    let parsed: serde_json::Map<String, serde_json::Value> =
        serde_json::from_value(load_json("query_parser", "parsed_queries.json")).unwrap();

    for (query, expected) in &parsed {
        let expected_semantic = expected["semantic_query"].as_str().unwrap();
        let expected_location = expected["location"].as_str();

        let (rust_semantic, rust_location) =
            rust_core::services::query_parser::parse_query(query);

        assert_eq!(
            rust_semantic, expected_semantic,
            "Query parser semantic mismatch for '{}'",
            query
        );

        assert_eq!(
            rust_location.as_deref(),
            expected_location,
            "Query parser location mismatch for '{}'",
            query
        );
    }
}

// =============================================================================
// Synonym Tests
// =============================================================================

#[test]
fn test_synonyms_match_python_static() {
    let golden_path = golden_dir().join("synonyms/synonyms.json");
    if !golden_path.exists() {
        eprintln!("Skipping: golden outputs not generated");
        return;
    }

    let expected: serde_json::Map<String, serde_json::Value> =
        serde_json::from_value(load_json("synonyms", "synonyms.json")).unwrap();

    for (word, python_synonyms) in &expected {
        let python_set: HashSet<String> = python_synonyms
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();

        let rust_set = rust_core::services::synonyms::get_synonyms(word);

        // Check that Rust static synonyms are a subset of Python synonyms
        // (Python may have additional WordNet synonyms)
        let rust_only: HashSet<_> = rust_set.difference(&python_set).collect();

        // All Rust synonyms should be in the Python set (Rust is a subset)
        // This is acceptable because we dropped WordNet
        if !rust_only.is_empty() {
            eprintln!(
                "Warning: Rust has extra synonyms for '{}' not in Python: {:?}",
                word, rust_only
            );
        }

        // The word itself should always be in both sets
        assert!(
            rust_set.contains(&word.to_lowercase()),
            "Rust synonyms for '{}' should contain the word itself",
            word
        );
    }
}

// =============================================================================
// Vector Search Tests
// =============================================================================

#[test]
fn test_vector_search_correctness() {
    let index = rust_core::search::VectorIndex::new("/tmp/test_cross_val_index").unwrap();

    // Create deterministic test embeddings
    let dim = 512;
    let mut embeddings: Vec<(String, Vec<f32>)> = Vec::new();
    for i in 0..100 {
        let mut emb = vec![0.0f32; dim];
        // Create embeddings pointing in slightly different directions
        emb[i % dim] = 1.0;
        emb[(i * 7) % dim] += 0.5;
        // Normalize
        let norm: f32 = emb.iter().map(|x| x * x).sum::<f32>().sqrt();
        for v in &mut emb {
            *v /= norm;
        }
        let id = format!("photo_{:04}", i);
        index.add(&id, &emb).unwrap();
        embeddings.push((id, emb));
    }

    // Search with the first embedding — should return itself as top result
    let results = index.search(&embeddings[0].1, 5).unwrap();
    assert_eq!(results[0].0, embeddings[0].0, "Top result should be itself");
    assert!(
        (results[0].1 - 1.0).abs() < 0.001,
        "Self-similarity should be ~1.0"
    );

    // Results should be sorted by score descending
    for i in 1..results.len() {
        assert!(
            results[i - 1].1 >= results[i].1,
            "Results should be sorted by score descending"
        );
    }

    // Cleanup
    let _ = std::fs::remove_file("/tmp/test_cross_val_index");
}

// =============================================================================
// Database Tests
// =============================================================================

#[test]
fn test_database_roundtrip() {
    let db = rust_core::database::Database::new(":memory:").unwrap();

    // Insert test photos
    for i in 0..10 {
        let photo = rust_core::database::PhotoRecord {
            id: format!("photo_{}", i),
            path: format!("/photos/test_{}.jpg", i),
            timestamp: Some(1700000000 + i * 3600),
            latitude: Some(37.0 + i as f64 * 0.1),
            longitude: Some(-122.0 + i as f64 * 0.1),
            description: Some(format!("Test photo {}", i)),
            tags: Some(format!("tag{},test", i)),
            camera_make: Some("TestCam".to_string()),
            camera_model: Some("Model X".to_string()),
        };
        db.insert_photo(&photo).unwrap();
    }

    // Verify count
    assert_eq!(db.photo_count().unwrap(), 10);

    // Verify get by ID
    let photo = db.get_photo("photo_5").unwrap().unwrap();
    assert_eq!(photo.path, "/photos/test_5.jpg");
    assert_eq!(photo.description, Some("Test photo 5".to_string()));

    // Verify time range filter
    let in_range = db
        .filter_by_time_range(1700000000 + 3600 * 2, 1700000000 + 3600 * 5)
        .unwrap();
    assert_eq!(in_range.len(), 4); // photos 2,3,4,5

    // Verify location filter
    let in_box = db.filter_by_location(37.2, 37.5, -121.9, -121.5).unwrap();
    assert!(!in_box.is_empty());

    // Verify folder filter
    let in_folder = db.filter_by_folder("/photos/").unwrap();
    assert_eq!(in_folder.len(), 10);

    // Verify delete
    assert!(db.delete_photo("photo_0").unwrap());
    assert_eq!(db.photo_count().unwrap(), 9);
    assert!(db.get_photo("photo_0").unwrap().is_none());

    // Verify pagination
    let page = db.get_photos(3, 0).unwrap();
    assert_eq!(page.len(), 3);
}
