// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rust_coreFFI)
import rust_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rust_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rust_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureRustCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The main entry point for the PhotoSearch Rust core.
 * Wraps all subsystems (CLIP, BLIP, vector search, database, services)
 * and exposes a high-level API to Swift via UniFFI.
 */
public protocol PhotoSearchEngineProtocol: AnyObject, Sendable {
    
    /**
     * Browse mode: return all photos with optional time/folder filtering, no query needed.
     */
    func browseAll(request: SearchRequest) throws  -> [SearchResult]
    
    /**
     * Delete all photos in a folder from the index and database.
     */
    func deleteFolder(folderPath: String) throws  -> UInt32
    
    /**
     * Delete a photo from the index and database.
     */
    func deletePhoto(photoId: String) throws  -> Bool
    
    /**
     * Encode an image file into a CLIP embedding.
     */
    func encodeImage(path: String) throws  -> [Float]
    
    /**
     * Encode a text query into a CLIP embedding.
     */
    func encodeText(query: String) throws  -> [Float]
    
    /**
     * Generate a caption for an image file.
     */
    func generateCaption(path: String) throws  -> String
    
    /**
     * Forward geocode a place name to coordinates (lat, lon).
     */
    func geocode(placeName: String)  -> [Double]?
    
    /**
     * Get photos with pagination.
     */
    func getPhotos(limit: UInt32, offset: UInt32) throws  -> [SearchResult]
    
    /**
     * Get the backend status.
     */
    func getStatus()  -> BackendStatus
    
    /**
     * Index a single photo (CLIP embedding + BLIP caption + EXIF + DB).
     */
    func indexPhoto(path: String) throws  -> IndexResult
    
    /**
     * Get the number of indexed photos.
     */
    func indexedCount()  -> UInt32
    
    /**
     * Health check - returns true if the engine is ready.
     */
    func isReady()  -> Bool
    
    /**
     * Rebuild image embeddings from the photo records already in the database.
     *
     * Used after a model change: the BLIP captions are kept (re-captioning is
     * the expensive part), only the SigLIP image embeddings are recomputed.
     * Photos whose image file is missing are skipped.
     */
    func reindexFromDatabase() throws  -> UInt32
    
    /**
     * Reverse geocode GPS coordinates to a place name.
     */
    func reverseGeocode(lat: Double, lon: Double)  -> String?
    
    /**
     * Search for photos matching a query.
     * Pipeline: parse query → resolve location → SigLIP text encode →
     * vector search (oversampled) → filter by time/location/folder → rank → top_k.
     */
    func search(request: SearchRequest) throws  -> [SearchResult]
    
}
/**
 * The main entry point for the PhotoSearch Rust core.
 * Wraps all subsystems (CLIP, BLIP, vector search, database, services)
 * and exposes a high-level API to Swift via UniFFI.
 */
open class PhotoSearchEngine: PhotoSearchEngineProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_rust_core_fn_clone_photosearchengine(self.pointer, $0) }
    }
    /**
     * Create a new PhotoSearchEngine.
     * data_dir: path to ~/Library/Application Support/PhotoSearch
     */
public convenience init(dataDir: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_constructor_photosearchengine_new(
        FfiConverterString.lower(dataDir),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_rust_core_fn_free_photosearchengine(pointer, $0) }
    }

    

    
    /**
     * Browse mode: return all photos with optional time/folder filtering, no query needed.
     */
open func browseAll(request: SearchRequest)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_browse_all(self.uniffiClonePointer(),
        FfiConverterTypeSearchRequest_lower(request),$0
    )
})
}
    
    /**
     * Delete all photos in a folder from the index and database.
     */
open func deleteFolder(folderPath: String)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_delete_folder(self.uniffiClonePointer(),
        FfiConverterString.lower(folderPath),$0
    )
})
}
    
    /**
     * Delete a photo from the index and database.
     */
open func deletePhoto(photoId: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_delete_photo(self.uniffiClonePointer(),
        FfiConverterString.lower(photoId),$0
    )
})
}
    
    /**
     * Encode an image file into a CLIP embedding.
     */
open func encodeImage(path: String)throws  -> [Float]  {
    return try  FfiConverterSequenceFloat.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_encode_image(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Encode a text query into a CLIP embedding.
     */
open func encodeText(query: String)throws  -> [Float]  {
    return try  FfiConverterSequenceFloat.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_encode_text(self.uniffiClonePointer(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Generate a caption for an image file.
     */
open func generateCaption(path: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_generate_caption(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Forward geocode a place name to coordinates (lat, lon).
     */
open func geocode(placeName: String) -> [Double]?  {
    return try!  FfiConverterOptionSequenceDouble.lift(try! rustCall() {
    uniffi_rust_core_fn_method_photosearchengine_geocode(self.uniffiClonePointer(),
        FfiConverterString.lower(placeName),$0
    )
})
}
    
    /**
     * Get photos with pagination.
     */
open func getPhotos(limit: UInt32, offset: UInt32)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_get_photos(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(limit),
        FfiConverterUInt32.lower(offset),$0
    )
})
}
    
    /**
     * Get the backend status.
     */
open func getStatus() -> BackendStatus  {
    return try!  FfiConverterTypeBackendStatus_lift(try! rustCall() {
    uniffi_rust_core_fn_method_photosearchengine_get_status(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Index a single photo (CLIP embedding + BLIP caption + EXIF + DB).
     */
open func indexPhoto(path: String)throws  -> IndexResult  {
    return try  FfiConverterTypeIndexResult_lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_index_photo(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Get the number of indexed photos.
     */
open func indexedCount() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rust_core_fn_method_photosearchengine_indexed_count(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Health check - returns true if the engine is ready.
     */
open func isReady() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_rust_core_fn_method_photosearchengine_is_ready(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Rebuild image embeddings from the photo records already in the database.
     *
     * Used after a model change: the BLIP captions are kept (re-captioning is
     * the expensive part), only the SigLIP image embeddings are recomputed.
     * Photos whose image file is missing are skipped.
     */
open func reindexFromDatabase()throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_reindex_from_database(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Reverse geocode GPS coordinates to a place name.
     */
open func reverseGeocode(lat: Double, lon: Double) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_rust_core_fn_method_photosearchengine_reverse_geocode(self.uniffiClonePointer(),
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lon),$0
    )
})
}
    
    /**
     * Search for photos matching a query.
     * Pipeline: parse query → resolve location → SigLIP text encode →
     * vector search (oversampled) → filter by time/location/folder → rank → top_k.
     */
open func search(request: SearchRequest)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypePhotoSearchError_lift) {
    uniffi_rust_core_fn_method_photosearchengine_search(self.uniffiClonePointer(),
        FfiConverterTypeSearchRequest_lower(request),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhotoSearchEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PhotoSearchEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PhotoSearchEngine {
        return PhotoSearchEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PhotoSearchEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PhotoSearchEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PhotoSearchEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhotoSearchEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> PhotoSearchEngine {
    return try FfiConverterTypePhotoSearchEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhotoSearchEngine_lower(_ value: PhotoSearchEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypePhotoSearchEngine.lower(value)
}




public struct BackendStatus {
    public var isReady: Bool
    public var indexedCount: UInt32
    public var version: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(isReady: Bool, indexedCount: UInt32, version: String) {
        self.isReady = isReady
        self.indexedCount = indexedCount
        self.version = version
    }
}

#if compiler(>=6)
extension BackendStatus: Sendable {}
#endif


extension BackendStatus: Equatable, Hashable {
    public static func ==(lhs: BackendStatus, rhs: BackendStatus) -> Bool {
        if lhs.isReady != rhs.isReady {
            return false
        }
        if lhs.indexedCount != rhs.indexedCount {
            return false
        }
        if lhs.version != rhs.version {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(isReady)
        hasher.combine(indexedCount)
        hasher.combine(version)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBackendStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BackendStatus {
        return
            try BackendStatus(
                isReady: FfiConverterBool.read(from: &buf), 
                indexedCount: FfiConverterUInt32.read(from: &buf), 
                version: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: BackendStatus, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.isReady, into: &buf)
        FfiConverterUInt32.write(value.indexedCount, into: &buf)
        FfiConverterString.write(value.version, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBackendStatus_lift(_ buf: RustBuffer) throws -> BackendStatus {
    return try FfiConverterTypeBackendStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBackendStatus_lower(_ value: BackendStatus) -> RustBuffer {
    return FfiConverterTypeBackendStatus.lower(value)
}


public struct IndexResult {
    public var photoId: String
    public var success: Bool
    public var error: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(photoId: String, success: Bool, error: String?) {
        self.photoId = photoId
        self.success = success
        self.error = error
    }
}

#if compiler(>=6)
extension IndexResult: Sendable {}
#endif


extension IndexResult: Equatable, Hashable {
    public static func ==(lhs: IndexResult, rhs: IndexResult) -> Bool {
        if lhs.photoId != rhs.photoId {
            return false
        }
        if lhs.success != rhs.success {
            return false
        }
        if lhs.error != rhs.error {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(photoId)
        hasher.combine(success)
        hasher.combine(error)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIndexResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IndexResult {
        return
            try IndexResult(
                photoId: FfiConverterString.read(from: &buf), 
                success: FfiConverterBool.read(from: &buf), 
                error: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: IndexResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.photoId, into: &buf)
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterOptionString.write(value.error, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIndexResult_lift(_ buf: RustBuffer) throws -> IndexResult {
    return try FfiConverterTypeIndexResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIndexResult_lower(_ value: IndexResult) -> RustBuffer {
    return FfiConverterTypeIndexResult.lower(value)
}


public struct SearchRequest {
    public var query: String
    public var topK: UInt32
    public var timeStart: Int64?
    public var timeEnd: Int64?
    public var location: String?
    public var folderPath: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(query: String, topK: UInt32, timeStart: Int64?, timeEnd: Int64?, location: String?, folderPath: String?) {
        self.query = query
        self.topK = topK
        self.timeStart = timeStart
        self.timeEnd = timeEnd
        self.location = location
        self.folderPath = folderPath
    }
}

#if compiler(>=6)
extension SearchRequest: Sendable {}
#endif


extension SearchRequest: Equatable, Hashable {
    public static func ==(lhs: SearchRequest, rhs: SearchRequest) -> Bool {
        if lhs.query != rhs.query {
            return false
        }
        if lhs.topK != rhs.topK {
            return false
        }
        if lhs.timeStart != rhs.timeStart {
            return false
        }
        if lhs.timeEnd != rhs.timeEnd {
            return false
        }
        if lhs.location != rhs.location {
            return false
        }
        if lhs.folderPath != rhs.folderPath {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(query)
        hasher.combine(topK)
        hasher.combine(timeStart)
        hasher.combine(timeEnd)
        hasher.combine(location)
        hasher.combine(folderPath)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchRequest {
        return
            try SearchRequest(
                query: FfiConverterString.read(from: &buf), 
                topK: FfiConverterUInt32.read(from: &buf), 
                timeStart: FfiConverterOptionInt64.read(from: &buf), 
                timeEnd: FfiConverterOptionInt64.read(from: &buf), 
                location: FfiConverterOptionString.read(from: &buf), 
                folderPath: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SearchRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.query, into: &buf)
        FfiConverterUInt32.write(value.topK, into: &buf)
        FfiConverterOptionInt64.write(value.timeStart, into: &buf)
        FfiConverterOptionInt64.write(value.timeEnd, into: &buf)
        FfiConverterOptionString.write(value.location, into: &buf)
        FfiConverterOptionString.write(value.folderPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchRequest_lift(_ buf: RustBuffer) throws -> SearchRequest {
    return try FfiConverterTypeSearchRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchRequest_lower(_ value: SearchRequest) -> RustBuffer {
    return FfiConverterTypeSearchRequest.lower(value)
}


public struct SearchResult {
    public var photoId: String
    public var score: Float
    public var path: String
    public var description: String?
    public var timestamp: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(photoId: String, score: Float, path: String, description: String?, timestamp: Int64?) {
        self.photoId = photoId
        self.score = score
        self.path = path
        self.description = description
        self.timestamp = timestamp
    }
}

#if compiler(>=6)
extension SearchResult: Sendable {}
#endif


extension SearchResult: Equatable, Hashable {
    public static func ==(lhs: SearchResult, rhs: SearchResult) -> Bool {
        if lhs.photoId != rhs.photoId {
            return false
        }
        if lhs.score != rhs.score {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(photoId)
        hasher.combine(score)
        hasher.combine(path)
        hasher.combine(description)
        hasher.combine(timestamp)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                photoId: FfiConverterString.read(from: &buf), 
                score: FfiConverterFloat.read(from: &buf), 
                path: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf), 
                timestamp: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.photoId, into: &buf)
        FfiConverterFloat.write(value.score, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
        FfiConverterOptionInt64.write(value.timestamp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}


public enum PhotoSearchError: Swift.Error {

    
    
    case ModelError(message: String
    )
    case DatabaseError(message: String
    )
    case IoError(message: String
    )
    case ImageError(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhotoSearchError: FfiConverterRustBuffer {
    typealias SwiftType = PhotoSearchError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PhotoSearchError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ModelError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .DatabaseError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .IoError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .ImageError(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PhotoSearchError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ModelError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .DatabaseError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .IoError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ImageError(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhotoSearchError_lift(_ buf: RustBuffer) throws -> PhotoSearchError {
    return try FfiConverterTypePhotoSearchError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhotoSearchError_lower(_ value: PhotoSearchError) -> RustBuffer {
    return FfiConverterTypePhotoSearchError.lower(value)
}


extension PhotoSearchError: Equatable, Hashable {}




extension PhotoSearchError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceDouble: FfiConverterRustBuffer {
    typealias SwiftType = [Double]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceDouble: FfiConverterRustBuffer {
    typealias SwiftType = [Double]

    public static func write(_ value: [Double], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterDouble.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Double] {
        let len: Int32 = try readInt(&buf)
        var seq = [Double]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterDouble.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [SearchResult]

    public static func write(_ value: [SearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchResult.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_rust_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_browse_all() != 62585) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_delete_folder() != 21330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_delete_photo() != 30434) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_encode_image() != 42752) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_encode_text() != 28673) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_generate_caption() != 31354) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_geocode() != 59178) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_get_photos() != 792) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_get_status() != 54543) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_index_photo() != 42888) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_indexed_count() != 41187) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_is_ready() != 10372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_reindex_from_database() != 65028) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_reverse_geocode() != 17189) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_method_photosearchengine_search() != 12953) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_constructor_photosearchengine_new() != 23319) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureRustCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all